apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    basicAuth: false
    secureJsonData:
      token: ${INFLUXDB_READ_TOKEN}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      httpMode: POST
    editable: true
